package com.alleato.dorado.engine;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.alleato.dorado.TestUtil;
import com.alleato.dorado.engine.Format.KdfParams;
import com.alleato.dorado.engine.Kdf.KdfPrf;
import java.util.Arrays;
import org.junit.jupiter.api.Test;

/**
 * Key-based derivation ({@code Kdf.deriveFromKey}/{@code deriveFromKeyWith}) and the
 * KDF parameter bounds. The known-answer vectors are the shared cross-language
 * fixtures in {@code docs/fixtures/derive-from-key.md}, generated by the Rust
 * reference; the property tests mirror the Rust engine's {@code kdf/tests.rs}.
 */
class KdfTest {
    private static final byte[] KEY32 =
        TestUtil.unhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");

    // ---- known-answer vectors (docs/fixtures/derive-from-key.md) ----

    @Test
    void katSkein32KeyEnc32Out() {
        assertArrayEquals(
            TestUtil.unhex("b638c503342dbd51bdfa8906b1cc6b18d7e54252b95e460c522ab3cd939802c6"),
            Kdf.deriveFromKeyWith(KdfPrf.SKEIN512, KEY32, "dorado/fixture/enc", 32));
    }

    @Test
    void katSkein32KeyMac64Out() {
        assertArrayEquals(
            TestUtil.unhex("6ae3f6f7518e9a4c8a7be8269deb848186beb64b5b43f0bafef81bce4b27d40e"
                + "f227e2064b941069cc6225cad0a39fcc22aba08fb87f3ba8aacdf4b70b100da6"),
            Kdf.deriveFromKeyWith(KdfPrf.SKEIN512, KEY32, "dorado/fixture/mac", 64));
    }

    @Test
    void katSkein16KeyEnc32Out() {
        // A non-32-byte key: the Skein-512 PRF accepts a key of any length.
        assertArrayEquals(
            TestUtil.unhex("3990e038c7235e62480afe99712203225194afb93910df4101447098e630d0e4"),
            Kdf.deriveFromKeyWith(KdfPrf.SKEIN512, TestUtil.unhex("a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5"),
                "dorado/fixture/enc", 32));
    }

    @Test
    void katSkein32KeyEmptyDomain32Out() {
        // The empty domain is valid (the DRDOkdrv prefix alone is the message).
        assertArrayEquals(
            TestUtil.unhex("5bba4214745b3932c1fc620c660b60a4058613ff2bd9d80224d472cd810f7a99"),
            Kdf.deriveFromKeyWith(KdfPrf.SKEIN512, KEY32, "", 32));
    }

    @Test
    void katBlake332KeyEnc32Out() {
        assertArrayEquals(
            TestUtil.unhex("8266bd0cfb0d73715aa841fe008c311a44d6b36e0aa01b94f13a90783fe62e1d"),
            Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, KEY32, "dorado/fixture/enc", 32));
    }

    @Test
    void katBlake332KeyMac64Out() {
        assertArrayEquals(
            TestUtil.unhex("ea38a1780192707518d15003262a66c245680a579762a7d863cc33078f2f6eaa"
                + "9a5086f70d00eb7c6cd12fdc7872e5a2023e63c28087631ce835d7e9c7264290"),
            Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, KEY32, "dorado/fixture/mac", 64));
    }

    // ---- properties (mirroring the Rust engine's kdf/tests.rs) ----

    @Test
    void deriveFromKeyIsDeterministicAndDomainSeparated() {
        byte[] master = new byte[32];
        Arrays.fill(master, (byte) 0x42);
        byte[] a = Kdf.deriveFromKey(master, "myapp/index", 32);
        byte[] b = Kdf.deriveFromKey(master, "myapp/index", 32);
        assertArrayEquals(a, b, "same key + domain must give the same bytes");

        byte[] c = Kdf.deriveFromKey(master, "myapp/data", 32);
        assertFalse(Arrays.equals(a, c), "a different domain must give a different key");

        byte[] other = new byte[32];
        Arrays.fill(other, (byte) 0x43);
        byte[] d = Kdf.deriveFromKey(other, "myapp/index", 32);
        assertFalse(Arrays.equals(a, d), "a different master must give a different key");

        // Children reveal nothing about each other or the master: at minimum,
        // none of them may equal the master or one another.
        assertFalse(Arrays.equals(a, master));
        assertFalse(Arrays.equals(c, master));
    }

    @Test
    void deriveFromKeySupportsArbitraryOutputLengths() {
        // The 1024-bit variant's raw mode needs 128-byte keys; Skein's output length
        // is free, so longer outputs must work and must not merely prefix-extend
        // shorter ones (the length is bound into the hash).
        byte[] master = new byte[32];
        Arrays.fill(master, (byte) 0x42);
        byte[] shortOut = Kdf.deriveFromKey(master, "myapp/index", 32);
        byte[] longOut = Kdf.deriveFromKey(master, "myapp/index", 128);
        assertFalse(Arrays.equals(shortOut, Arrays.copyOfRange(longOut, 0, 32)),
            "output length is part of Skein's config, not a truncation");
    }

    @Test
    void deriveFromKeyDefaultMatchesSkeinPrf() {
        // deriveFromKey is defined as deriveFromKeyWith(SKEIN512, ..); the two must
        // be byte-for-byte identical so the default is never a silent change.
        byte[] master = new byte[32];
        Arrays.fill(master, (byte) 0x42);
        assertArrayEquals(
            Kdf.deriveFromKey(master, "myapp/index", 32),
            Kdf.deriveFromKeyWith(KdfPrf.SKEIN512, master, "myapp/index", 32));
    }

    @Test
    void deriveFromKeyWithBlake3IsDeterministicDomainSeparatedAndDistinct() {
        byte[] master = new byte[32];
        Arrays.fill(master, (byte) 0x42);
        byte[] a = Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, master, "myapp/index", 32);
        byte[] b = Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, master, "myapp/index", 32);
        assertArrayEquals(a, b, "same key + domain must give the same bytes");

        byte[] c = Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, master, "myapp/data", 32);
        assertFalse(Arrays.equals(a, c), "a different domain must give a different key");
        assertFalse(Arrays.equals(a, master), "a child never equals the master");

        // The two PRFs are independent functions: the same key/domain under Skein
        // and under BLAKE3 must not coincide.
        byte[] skein = Kdf.deriveFromKeyWith(KdfPrf.SKEIN512, master, "myapp/index", 32);
        assertFalse(Arrays.equals(a, skein), "BLAKE3 and Skein fan-outs must differ");
    }

    @Test
    void deriveFromKeyWithBlake3SupportsArbitraryOutputLengths() {
        // BLAKE3 is an XOF, so any output length works and a longer output is the
        // prefix-extension of a shorter one.
        byte[] master = new byte[32];
        Arrays.fill(master, (byte) 0x42);
        byte[] shortOut = Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, master, "myapp/index", 32);
        byte[] longOut = Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, master, "myapp/index", 128);
        assertArrayEquals(shortOut, Arrays.copyOfRange(longOut, 0, 32),
            "BLAKE3 is an XOF: a shorter output is the prefix of a longer one");
    }

    @Test
    void deriveFromKeyWithBlake3RejectsNon32ByteKey() {
        assertThrows(IllegalArgumentException.class,
            () -> Kdf.deriveFromKeyWith(KdfPrf.BLAKE3, new byte[16], "myapp/index", 32));
    }

    // ---- parameter bounds ----

    @Test
    void validateRejectsZeroPbkdf2Rounds() {
        // Zero rounds would "derive" an all-zero key without error; sane counts pass
        // and the existing upper bound still holds.
        assertDoesNotThrow(() -> Kdf.validate(KdfParams.pbkdf2(600_000)));
        assertThrows(MalformedContainerException.class, () -> Kdf.validate(KdfParams.pbkdf2(0)));
        assertThrows(MalformedContainerException.class, () -> Kdf.validate(KdfParams.pbkdf2(60_000_000L)));
    }
}
