"""Key-based derivation (derive_from_key / derive_from_key_with): known-answer
vectors generated from the Rust reference (see ../../docs/fixtures/derive-from-key.md),
the determinism/domain-separation properties, and the KDF cost validate() bounds.
"""

import pytest

from dorado import KdfParams, KdfPrf, MalformedContainer, derive_from_key, derive_from_key_with, kdf

# ---------------------------------------------------------------------------
# Known-answer vectors from docs/fixtures/derive-from-key.md, generated by and
# verified against the Rust reference. Every port's suite hardcodes these; this
# is the actual cross-language compatibility proof.
# ---------------------------------------------------------------------------

KAT_VECTORS = [
    dict(
        name="skein_32key_enc_32out",
        prf=KdfPrf.SKEIN512,
        key=bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
        domain="dorado/fixture/enc",
        out_len=32,
        out=bytes.fromhex("b638c503342dbd51bdfa8906b1cc6b18d7e54252b95e460c522ab3cd939802c6"),
    ),
    dict(
        name="skein_32key_mac_64out",
        prf=KdfPrf.SKEIN512,
        key=bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
        domain="dorado/fixture/mac",
        out_len=64,
        out=bytes.fromhex(
            "6ae3f6f7518e9a4c8a7be8269deb848186beb64b5b43f0bafef81bce4b27d40e"
            "f227e2064b941069cc6225cad0a39fcc22aba08fb87f3ba8aacdf4b70b100da6"
        ),
    ),
    dict(
        # A non-32-byte key: the Skein-512 PRF accepts a key of any length.
        name="skein_16key_enc_32out",
        prf=KdfPrf.SKEIN512,
        key=bytes.fromhex("a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5"),
        domain="dorado/fixture/enc",
        out_len=32,
        out=bytes.fromhex("3990e038c7235e62480afe99712203225194afb93910df4101447098e630d0e4"),
    ),
    dict(
        # The empty domain is valid (the DRDOkdrv prefix alone is the message).
        name="skein_32key_empty_domain_32out",
        prf=KdfPrf.SKEIN512,
        key=bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
        domain="",
        out_len=32,
        out=bytes.fromhex("5bba4214745b3932c1fc620c660b60a4058613ff2bd9d80224d472cd810f7a99"),
    ),
    dict(
        name="blake3_32key_enc_32out",
        prf=KdfPrf.BLAKE3,
        key=bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
        domain="dorado/fixture/enc",
        out_len=32,
        out=bytes.fromhex("8266bd0cfb0d73715aa841fe008c311a44d6b36e0aa01b94f13a90783fe62e1d"),
    ),
    dict(
        name="blake3_32key_mac_64out",
        prf=KdfPrf.BLAKE3,
        key=bytes.fromhex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
        domain="dorado/fixture/mac",
        out_len=64,
        out=bytes.fromhex(
            "ea38a1780192707518d15003262a66c245680a579762a7d863cc33078f2f6eaa"
            "9a5086f70d00eb7c6cd12fdc7872e5a2023e63c28087631ce835d7e9c7264290"
        ),
    ),
]


@pytest.mark.parametrize("v", KAT_VECTORS, ids=[v["name"] for v in KAT_VECTORS])
def test_known_answer(v):
    assert derive_from_key_with(v["prf"], v["key"], v["domain"], v["out_len"]) == v["out"], v["name"]
    if v["prf"] == KdfPrf.SKEIN512:
        # The default, PRF-less form is defined as the Skein-512 case and must
        # match the same vectors byte-for-byte.
        assert derive_from_key(v["key"], v["domain"], v["out_len"]) == v["out"], v["name"]


# ---------------------------------------------------------------------------
# Properties, mirroring the Rust reference's kdf tests.
# ---------------------------------------------------------------------------

MASTER = bytes([0x42]) * 32


def test_derive_from_key_is_deterministic_and_domain_separated():
    a = derive_from_key(MASTER, "myapp/index", 32)
    assert derive_from_key(MASTER, "myapp/index", 32) == a, "same key + domain must give the same bytes"

    c = derive_from_key(MASTER, "myapp/data", 32)
    assert c != a, "a different domain must give a different key"

    d = derive_from_key(bytes([0x43]) * 32, "myapp/index", 32)
    assert d != a, "a different master must give a different key"

    # Children reveal nothing about each other or the master: at minimum, none
    # of them may equal the master or one another.
    assert a != MASTER
    assert c != MASTER


def test_derive_from_key_supports_arbitrary_output_lengths():
    # The 1024-bit variant's raw mode needs 128-byte keys; Skein's output length
    # is free, so longer outputs must work and must not merely prefix-extend
    # shorter ones (the length is bound into the hash).
    short = derive_from_key(MASTER, "myapp/index", 32)
    long = derive_from_key(MASTER, "myapp/index", 128)
    assert len(long) == 128
    assert long[:32] != short, "output length is part of Skein's config, not a truncation"


def test_derive_from_key_default_matches_skein_prf():
    # derive_from_key is defined as derive_from_key_with(SKEIN512, ..); the two
    # must be byte-for-byte identical so the default is never a silent change.
    assert derive_from_key(MASTER, "myapp/index", 32) == derive_from_key_with(
        KdfPrf.SKEIN512, MASTER, "myapp/index", 32
    )


def test_derive_from_key_with_blake3_is_deterministic_domain_separated_and_distinct():
    a = derive_from_key_with(KdfPrf.BLAKE3, MASTER, "myapp/index", 32)
    assert derive_from_key_with(KdfPrf.BLAKE3, MASTER, "myapp/index", 32) == a

    c = derive_from_key_with(KdfPrf.BLAKE3, MASTER, "myapp/data", 32)
    assert c != a, "a different domain must give a different key"
    assert a != MASTER, "a child never equals the master"

    # The two PRFs are independent functions: the same key/domain under Skein
    # and under BLAKE3 must not coincide.
    assert a != derive_from_key_with(KdfPrf.SKEIN512, MASTER, "myapp/index", 32)


def test_derive_from_key_with_blake3_supports_arbitrary_output_lengths():
    # BLAKE3 is an XOF, so any output length works and a shorter output is the
    # prefix of a longer one (unlike Skein, where the length is bound in).
    short = derive_from_key_with(KdfPrf.BLAKE3, MASTER, "myapp/index", 32)
    long = derive_from_key_with(KdfPrf.BLAKE3, MASTER, "myapp/index", 128)
    assert long[:32] == short, "BLAKE3 is an XOF: a shorter output is the prefix of a longer one"


def test_derive_from_key_with_blake3_rejects_non_32_byte_key():
    with pytest.raises(ValueError, match="32-byte key"):
        derive_from_key_with(KdfPrf.BLAKE3, bytes(16), "myapp/index", 32)


# ---------------------------------------------------------------------------
# validate() bounds on untrusted cost parameters.
# ---------------------------------------------------------------------------


def test_validate_rejects_zero_and_absurd_pbkdf2_rounds():
    kdf.validate(KdfParams.pbkdf2(600_000))  # the default is fine
    # Zero rounds would "derive" an all-zero key without error.
    with pytest.raises(MalformedContainer, match="pbkdf2 rounds must be nonzero"):
        kdf.validate(KdfParams.pbkdf2(0))
    with pytest.raises(MalformedContainer, match="pbkdf2 rounds too large"):
        kdf.validate(KdfParams.pbkdf2(2**32 - 1))
