"""Raw-key authenticated mode (encrypt-then-MAC, caller-supplied key, no password,
no KDF): known-answer vectors generated from the Rust reference, plus the
round-trip/tamper/wrong-key/mismatched-parameter security properties. See
../../docs/spec.md, "Raw-key modes", and ../../docs/fixtures/raw-authenticated.md.
"""

import pytest

from dorado import (
    MAC_BLAKE3,
    MAC_HMAC,
    MAC_SKEIN,
    AuthError,
    DoradoError,
    InvalidParams,
    T256,
    T512,
    T1024,
    decrypt_raw_authenticated,
    encrypt_raw_authenticated,
    raw_ctr,
)

# ---------------------------------------------------------------------------
# Known-answer vectors from docs/fixtures/raw-authenticated.md, generated by and
# verified against the Rust reference (dorado-cli --authenticated). Every port's
# suite hardcodes these; this is the actual cross-language compatibility proof.
# ---------------------------------------------------------------------------

KAT_VECTORS = [
    dict(
        name="t256_skein_single",
        variant=T256,
        mac=MAC_SKEIN,
        chunk_size=65536,
        key=bytes.fromhex(
            "1111111111111111111111111111111111111111111111111111111111111111"
        ),
        iv=bytes.fromhex(
            "0202020202020202020202020202020202020202020202020202020202020202"
        ),
        tweak=bytes.fromhex("00000000000000000000000000000000"),
        plaintext=bytes.fromhex(
            "65786572636973696e6720746865207261772061757468656e7469636174656420636f6e737472756374696f6e"
            "206163726f7373206c616e677561676573"
        ),
        ciphertext=bytes.fromhex(
            "010000003ef672003645a72252f71193824a177172deeb59677ab44c27f9d766e9970fbd3d64035d624cf2ab16"
            "7e9278595a5fb8f39bbd7e178d5f5e2054d2fc14b8961a7bb9296d0da601e3aba580a70532ad6b83e8fc105062"
            "0de95d5ba50e545621"
        ),
    ),
    dict(
        name="t256_hmac_single",
        variant=T256,
        mac=MAC_HMAC,
        chunk_size=65536,
        key=bytes.fromhex(
            "1111111111111111111111111111111111111111111111111111111111111111"
        ),
        iv=bytes.fromhex(
            "0202020202020202020202020202020202020202020202020202020202020202"
        ),
        tweak=bytes.fromhex("00000000000000000000000000000000"),
        plaintext=bytes.fromhex(
            "65786572636973696e6720746865207261772061757468656e7469636174656420636f6e737472756374696f6e"
            "206163726f7373206c616e677561676573"
        ),
        ciphertext=bytes.fromhex(
            "010000003ef672003645a72252f71193824a177172deeb59677ab44c27f9d766e9970fbd3d64035d624cf2ab16"
            "7e9278595a5fb8f39bbd7e178d5f5e2054d2fc14b8968381b4daded95b311377792e768eee91a63e2346b585ac"
            "3eda337afd6ed6dfff"
        ),
    ),
    dict(
        name="t256_blake3_single",
        variant=T256,
        mac=MAC_BLAKE3,
        chunk_size=65536,
        key=bytes.fromhex(
            "1111111111111111111111111111111111111111111111111111111111111111"
        ),
        iv=bytes.fromhex(
            "0202020202020202020202020202020202020202020202020202020202020202"
        ),
        tweak=bytes.fromhex("00000000000000000000000000000000"),
        plaintext=bytes.fromhex(
            "65786572636973696e6720746865207261772061757468656e7469636174656420636f6e737472756374696f6e"
            "206163726f7373206c616e677561676573"
        ),
        ciphertext=bytes.fromhex(
            "010000003ef672003645a72252f71193824a177172deeb59677ab44c27f9d766e9970fbd3d64035d624cf2ab16"
            "7e9278595a5fb8f39bbd7e178d5f5e2054d2fc14b896815761a7e9f6762a4a0dd0de969ab2bf00e7d04304b45f"
            "b53984b5e29deb9834"
        ),
    ),
    dict(
        name="t512_skein_single",
        variant=T512,
        mac=MAC_SKEIN,
        chunk_size=65536,
        key=bytes.fromhex(
            "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
            "11111111111111111111111111111111111111"
        ),
        iv=bytes.fromhex(
            "020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202"
            "02020202020202020202020202020202020202"
        ),
        tweak=bytes.fromhex("00000000000000000000000000000000"),
        plaintext=bytes.fromhex(
            "65786572636973696e6720746865207261772061757468656e7469636174656420636f6e737472756374696f6e"
            "206163726f7373206c616e677561676573"
        ),
        ciphertext=bytes.fromhex(
            "010000003e9b6cf38a329d996ff458a80a5993a2fbbb8b29237d5561b5a7883b2b47eb06ca7ea842953feb5ebf"
            "6aec6b95d17c646a8294b66e6f04a98ffc255ee4e62d44f0b6fa861dc2ea6a8be5fd71b60863900177af52c649"
            "ede00952bde11f1394"
        ),
    ),
    dict(
        name="t1024_skein_single",
        variant=T1024,
        mac=MAC_SKEIN,
        chunk_size=65536,
        key=bytes.fromhex(
            "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
            "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
            "1111111111111111111111111111111111111111111111111111111111111111111111111111"
        ),
        iv=bytes.fromhex(
            "020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202"
            "020202020202020202020202020202020202020202020202020202020202020202020202020202020202020202"
            "0202020202020202020202020202020202020202020202020202020202020202020202020202"
        ),
        tweak=bytes.fromhex("00000000000000000000000000000000"),
        plaintext=bytes.fromhex(
            "65786572636973696e6720746865207261772061757468656e7469636174656420636f6e737472756374696f6e"
            "206163726f7373206c616e677561676573"
        ),
        ciphertext=bytes.fromhex(
            "010000003ef55cd4e609b16c109712985cc509501cd194befaa963a620c123816bd9fd494f85cd899f2a52b005"
            "a0fb1105fe6706ceb7f937573662a11b14b53c939c8ade26889e72113babe3236093b8855432a67c45888b131b"
            "e41f72cd890a724f0f"
        ),
    ),
    dict(
        name="t256_skein_multichunk",
        variant=T256,
        mac=MAC_SKEIN,
        chunk_size=1024,
        key=bytes.fromhex(
            "1111111111111111111111111111111111111111111111111111111111111111"
        ),
        iv=bytes.fromhex(
            "0202020202020202020202020202020202020202020202020202020202020202"
        ),
        tweak=bytes.fromhex("00000000000000000000000000000000"),
        plaintext=bytes.fromhex(
            "61206c6f6e676572207061796c6f6164206d65616e7420746f207370616e206d756c7469706c65206f6e652d6b"
            "696c6f627974652061757468656e74696361746564206368756e6b7320736f207468652063726f73732d6c616e"
            "6775616765206669787475726520616c736f206578657263697365732074686520636f6e74696e756f75732063"
            "6f756e74657220616e64207065722d6672616d652074616767696e67206163726f7373206368756e6b20626f75"
            "6e6461726965732c206e6f74206a75737420612073696e676c65206672616d652e207878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878"
            "78787878787878787878787878787878787878"
        ),
        ciphertext=bytes.fromhex(
            "0000000400f22a092b48a93449b906d28f4e1d30649ff11c6761b40436f8837cfa9715f834310c46654feabc43"
            "7288741b5f16b5ff8bab79018d524a3a5bc2f307b486959bdb2b43f608b3a624af1d302506d312ff8c536eee10"
            "f553ab87e39697249ea5f92050c9ee832a8c8c2d7e4dffba0d5b3650a65d4ec8ef92c6ec60d2030c334e56e091"
            "654db2e1ad8e3cbc921f7092bc34afc8d41226526e31b1da8240da06169ef5643695b82247984b334e4842a34b"
            "88789ff0886098e002521245065ba7e1550136a7817ed24f451cc0a1f8c778dbc3febc1e0de9fd4810f7077c85"
            "a8ac7dd49b0c34546708ccba6babcc1391a2f0d2d0e44f848f5f8d894f48d2b2f0f8854bb6257179d883d55cf7"
            "b21c5c764fb1008f582917a6d54ddd75209c39814a1f0c795fcdcf11fb69fa36bbbdf9d798338cf01a20326fc4"
            "c4d9e0ce7d874cd0f6b5bc493dcfaac173f8259f597a1d28c72e92e2b47a7573857e0dd47b1ef6192b97434fdc"
            "7572f5ed93c4eee4b0466bed9246a037334cc319ab9d06830edccd3bca5ef2e69769a4d2a57b5d3cde17381ba1"
            "d5dee0f828ff67b0b31b1f78d6684a2ef8596c0cf60ba76834ce054fb4f7e524df218c21c2f552f74e445efbbc"
            "24c8b29df788c92b0c0a08251583fa6f0dbc187ff8dc11f572160e9f813aa04868a69ca4c0f8b111d5213ef4d7"
            "e7be43d34c4db41241764093e1f259ce6430b754aaeeaa5fd010334928380060453213fde390d7d1b36f0f3424"
            "2b5856df0e13f6bcc351c557c3b4b0fb5db5382bf229818a094b9ad714d0d73ba734da002a4c1fdf9613c25556"
            "ed9cb350f1d17a863ddb72a13688f51e7e56f9f6d97fcf1b7f050c4a5f45c0760ae09f19fdccebc47d48cb6a22"
            "de0b2327a30f19038b2bf06e69e3229fd9db1b55dad18a30bc67f3b4670a35b9c17884feb94f6c7b1183faadb7"
            "c60768c34e098754d59ce4b057249e5a7e0fc37a84925d8582a996e3ff38a3e844711f444a8ad1bbcda549b9d3"
            "b3d1f1a1c436cca8bd093056207951372661e6f1d673d04279a7bbb35bccb5bc5b16053506d66c0171417a7428"
            "b40e117b21f20d73ffd4a0b4c31a8314fc41415f23ea59fb375e090a1442f3a99b46ffcb2db05ae459912ace29"
            "2e382feddede89ce478b2f09072e8415442d5208e7be684406bcd8d1daf671471c875e9473d23be31ae5cb4dd5"
            "9166fca876d33c1bc4354275ac62acc6e797e78c6255fc4aa500776fdd556364c98c0c0bdb00f897bdf6e782a7"
            "4a65b67539a0b5d2d0d18fb3368d45913b2e1cac5e4b6c6c790c0327b2fd8569c1182a945859c9fed3e0009cf6"
            "067ff4910f6fab39d77d8da052a1aec80b115391f717475e9f8ab01ca3a2e7f4ed45e15cb8590c01f6274aae9b"
            "75e3852fce44b07f41bfe18777395112bbafbfab1be72df1be7a16e502d3385ff547f083bab16cd43d57f00d8f"
            "cce0595e3b57f18b2ca2da0f94f8c42bdc5237a41673617ea43d010000018657d51b2abd9a7809306c46b7c102"
            "0a729dd1efddc182b7412e45fae64f45b3e33ad6440f1d827977eb3f5b3e583d718a8c0fb43d4b00d557dc9a7a"
            "feef9a361a3a18014fa545baa6a184836a082798c4de40c82b96a5a5cd557fb4a8e15d6d0d5f411e6083b3f2c1"
            "4b716c7a4d5167e077b1a2ded34f9e30eea332309801843ea53f53bea4f265ee8176a28c08b80f0189d754bef3"
            "99ebd1c4407432af717dd7b949f8eee02cf4dca067b4b6cd7f50dd53b8bff3e35af9352d0d62b3ccf4d3f5af2e"
            "b8ed593200c1826984322967bf1bd6f682ff312690bf64c277bad2ab306931e97e23dd5790127921af7d166174"
            "56c585b835117b08621c40dddd38929d0728da224e31dd1d2d5461b2ce6e162f41436c92b5515223aa3f9572ab"
            "9ede606fb0c2c94545cc6221179aa6c11508e2dc6f1be11d8c82d051609ca26b397fffdbfd26d76301e1ecc03a"
            "b9699df7863eeee1a9bdd861c71319b3195e32215a56ada80234a28b8c31376c6846df120d9f0eb0979b618dd6"
            "2b78e2fb886e7412cd9137451c75ace33797024dadf2784b969e1c56a81088dd5ac19c8a6061d2c9519c430917"
            "0d8192"
        ),
    ),
]


@pytest.mark.parametrize("v", KAT_VECTORS, ids=[v["name"] for v in KAT_VECTORS])
def test_known_answer_encrypt(v):
    ct = encrypt_raw_authenticated(v["variant"], v["key"], v["tweak"], v["iv"], v["mac"], v["chunk_size"], v["plaintext"])
    assert ct == v["ciphertext"], v["name"]


@pytest.mark.parametrize("v", KAT_VECTORS, ids=[v["name"] for v in KAT_VECTORS])
def test_known_answer_decrypt(v):
    pt = decrypt_raw_authenticated(v["variant"], v["key"], v["tweak"], v["iv"], v["mac"], v["chunk_size"], v["ciphertext"])
    assert pt == v["plaintext"], v["name"]


# ---------------------------------------------------------------------------
# Round trip / security properties.
# ---------------------------------------------------------------------------

KEY_256 = bytes([0x11]) * 32
KEY_512 = bytes([0x11]) * 64
KEY_1024 = bytes([0x11]) * 128
TWEAK = bytes(16)
IV_256 = bytes([0x02]) * 32


def test_round_trip():
    pt = b"a message that spans more than nothing"
    ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, pt)
    assert ct != pt
    assert decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, ct) == pt


def test_round_trip_each_variant():
    for variant, key in [(T256, KEY_256), (T512, KEY_512), (T1024, KEY_1024)]:
        iv = bytes([0x02]) * len(key)
        pt = b"payload exercising each Threefish width"
        ct = encrypt_raw_authenticated(variant, key, TWEAK, iv, MAC_SKEIN, 4096, pt)
        assert decrypt_raw_authenticated(variant, key, TWEAK, iv, MAC_SKEIN, 4096, ct) == pt


def test_round_trip_non_256_variant_arbitrary_key_iv():
    key = bytes(range(64))
    iv = bytes(255 - i for i in range(64))
    pt = b"arbitrary key and iv for a non-256 variant"
    ct = encrypt_raw_authenticated(T512, key, TWEAK, iv, MAC_SKEIN, 4096, pt)
    assert decrypt_raw_authenticated(T512, key, TWEAK, iv, MAC_SKEIN, 4096, ct) == pt


def test_ciphertext_differs_from_bare_raw_ctr():
    # Same key/tweak/iv into both paths must not produce related output on the
    # ciphertext bytes preceding the tag: the authenticated path derives its own
    # encryption subkey rather than reusing the raw key directly.
    pt = b"identical plaintext into both raw paths"
    bare = raw_ctr(T256, KEY_256, TWEAK, IV_256, pt)
    authenticated = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, pt)
    assert authenticated[: len(bare)] != bare


def test_wrong_key_rejected():
    ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, b"secret")
    wrong_key = bytes([0x99]) * 32
    with pytest.raises(AuthError):
        decrypt_raw_authenticated(T256, wrong_key, TWEAK, IV_256, MAC_SKEIN, 4096, ct)


def test_tampering_rejected():
    ct = bytearray(encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, b"secret"))
    ct[-1] ^= 1
    with pytest.raises(AuthError):
        decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, bytes(ct))


def test_mismatched_tweak_rejected():
    # Neither tweak nor iv is stored anywhere (raw mode has no header): both are
    # bound into frame 0's AAD, so decrypting with the wrong one must fail rather
    # than silently produce different plaintext.
    pt = b"bound parameters must not be swappable"
    ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, pt)
    other_tweak = bytes([0x7F]) * 16
    with pytest.raises(AuthError):
        decrypt_raw_authenticated(T256, KEY_256, other_tweak, IV_256, MAC_SKEIN, 4096, ct)


def test_mismatched_iv_rejected():
    pt = b"bound parameters must not be swappable"
    ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, pt)
    other_iv = bytes([0x7F]) * 32
    with pytest.raises(AuthError):
        decrypt_raw_authenticated(T256, KEY_256, TWEAK, other_iv, MAC_SKEIN, 4096, ct)


def test_every_mac_round_trips_and_rejects_tampering():
    for mac in [MAC_SKEIN, MAC_HMAC, MAC_BLAKE3]:
        pt = b"plaintext authenticated by each MAC in turn"
        ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, mac, 4096, pt)
        assert decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, mac, 4096, ct) == pt, mac

        tampered = bytearray(ct)
        tampered[-1] ^= 1
        with pytest.raises(AuthError):
            decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, mac, 4096, bytes(tampered))


def test_multi_chunk_round_trip_and_rejects_early_chunk_tampering():
    pt = bytes(i & 0xFF for i in range(200))
    ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 64, pt)
    assert decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 64, ct) == pt

    # Flip a byte roughly inside the first chunk's ciphertext; its tag must reject
    # it before any later chunk is decrypted.
    tampered = bytearray(ct)
    pos = len(ct) // 3
    tampered[pos] ^= 1
    with pytest.raises(AuthError):
        decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 64, bytes(tampered))


def test_rejects_truncation():
    pt = bytes(i & 0xFF for i in range(200))
    ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 64, pt)
    for cut in (1, 33, 80, 150):
        truncated = ct[: len(ct) - cut]
        with pytest.raises(DoradoError):
            decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 64, truncated)


def test_rejects_wrong_key_length():
    with pytest.raises(InvalidParams):
        encrypt_raw_authenticated(T256, bytes(16), TWEAK, bytes(32), MAC_SKEIN, 4096, b"data")


def test_auth_failure_does_not_distinguish_wrong_key_from_tampering():
    ct = encrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, b"secret")

    wrong_key = bytes([0x99]) * 32
    with pytest.raises(AuthError) as wrong_exc:
        decrypt_raw_authenticated(T256, wrong_key, TWEAK, IV_256, MAC_SKEIN, 4096, ct)

    tampered = bytearray(ct)
    tampered[-1] ^= 1
    with pytest.raises(AuthError) as tamper_exc:
        decrypt_raw_authenticated(T256, KEY_256, TWEAK, IV_256, MAC_SKEIN, 4096, bytes(tampered))

    assert str(wrong_exc.value) == str(tamper_exc.value)
